# This is a basic workflow to help you get started with Actions

name: Deploy to Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "docker-mooc-pt1-app" #Must be unique in Heroku
          heroku_email: "essi.jukkala@gmail.com"
          usedocker: true
